package com.vivek.wallet_service.entity;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "users")
@Getter
@Setter
public class User {
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;
    private String name;
    private String email;
    private String password;

}// An Entity has been created to represent the User table in the database. It has three fields: id, name, and email. The id field is annotated with @Id and @GeneratedValue to indicate that it is the primary key and will be automatically generated by the database. The class is also annotated with @Entity and @Table to specify that it is a JPA entity and to define the table name in the database. The @Getter and @Setter annotations from Lombok are used to automatically generate getter and setter methods for the fields.
